version: '1.0'
services:
  database:
    image: mysql:8.0.35
    command: '--default-authentication-plugin=caching_sha2_password'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      hilla_net:
        ipv4_address: 172.42.0.2
    ports:
      - '3306:3306'
  site:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      hilla_net:
        ipv4_address: 172.42.0.3
    ports:
      - '8090:8090'
      - '8089:8089'
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - SITE_HOST=${SITE_HOST}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SOCKET_IO_IP_ADDRESS=${SOCKET_IO_IP_ADDRESS}
      - SOCKET_IO_PORT=${SOCKET_IO_PORT}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - VITE_SITE_URL=${VITE_SITE_URL}
      - VITE_SITE_ENVIRONMENT=${VITE_SITE_ENVIRONMENT}
      - VITE_ASSETS_FOLDER=${VITE_ASSETS_FOLDER}
    depends_on:
      - database
networks:
  hilla_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/28
          gateway: 172.42.0.1
