version: '1.0'
services:
  database:
    image: mysql:8.0.35
    command: '--default-authentication-plugin=caching_sha2_password'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DB_NAME}
    networks:
      hilla_net:
        ipv4_address: 172.42.0.2
    ports:
      - '3306:3306'
  site:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      hilla_net:
        ipv4_address: 172.42.0.3
    ports:
      - '8090:8090'
      - '8089:8089'
    environment:
      - AUTH_SECRET=${DOCKER_AUTH_SECRET}
      - SITE_HOST=${DOCKER_SITE_HOST}
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_PORT=${DOCKER_DB_PORT}
      - DB_NAME=${DOCKER_DB_NAME}
      - DB_USERNAME=${DOCKER_DB_USERNAME}
      - DB_PASSWORD=${DOCKER_DB_PASSWORD}
      - SOCKET_IO_IP_ADDRESS=${DOCKER_SOCKET_IO_IP_ADDRESS}
      - SOCKET_IO_PORT=${DOCKER_SOCKET_IO_PORT}
      - SPRING_MAIL_HOST=${DOCKER_SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${DOCKER_SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${DOCKER_SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${DOCKER_SPRING_MAIL_PASSWORD}
      - VITE_SITE_URL=${DOCKER_VITE_SITE_URL}
      - VITE_SITE_ENVIRONMENT=${DOCKER_VITE_SITE_ENVIRONMENT}
      - VITE_ASSETS_FOLDER=${DOCKER_VITE_ASSETS_FOLDER}
    depends_on:
      - database
networks:
  hilla_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/28
          gateway: 172.42.0.1
